CREATE TABLE IF NOT EXISTS `user` (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  last_login_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scan_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  session_id VARCHAR(100) DEFAULT NULL,
  mode VARCHAR(30) NOT NULL,
  trigger_command VARCHAR(255) DEFAULT NULL,
  scene VARCHAR(255) DEFAULT NULL,
  narration TEXT,
  position_summary VARCHAR(255) DEFAULT NULL,
  captured_at DATETIME NOT NULL,
  latitude DOUBLE DEFAULT NULL,
  longitude DOUBLE DEFAULT NULL,
  location_text VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scan_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  record_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  position VARCHAR(100) DEFAULT NULL,
  confidence INT DEFAULT NULL,
  attributes_json TEXT,
  is_primary TINYINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_username ON `user`(username);
CREATE UNIQUE INDEX IF NOT EXISTS uk_phone ON `user`(phone);
CREATE UNIQUE INDEX IF NOT EXISTS uk_email ON `user`(email);
CREATE INDEX IF NOT EXISTS idx_scan_record_user_time ON scan_record(user_id, captured_at);
CREATE INDEX IF NOT EXISTS idx_scan_record_session ON scan_record(session_id);
CREATE INDEX IF NOT EXISTS idx_scan_item_record ON scan_item(record_id);
