server.port=8080
spring.application.name=demo
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/homework?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.configuration.map-underscore-to-camel-case=true
vision.provider=qwen
vision.qwen.base-url=https://dashscope.aliyuncs.com
vision.qwen.api-key=sk-31c955c0640c492f8f18f84fe54deda4
vision.qwen.vl-model=qwen-vl-plus-latest
vision.qwen.tts-model=qwen-tts
vision.qwen.tts-voice=Cherry
vision.qwen.tts-format=mp3
