server.port=8080
spring.application.name=demo
vision.provider=qwen
vision.qwen.base-url=https://dashscope.aliyuncs.com
vision.qwen.api-key=sk-31c955c0640c492f8f18f84fe54deda4
vision.qwen.vl-model=qwen-vl-plus-latest
vision.qwen.tts-model=qwen-tts
vision.qwen.tts-voice=Cherry
vision.qwen.tts-format=mp3
